variable "ami" {}
variable "subnet-id" {}
variable "jenkins-sg" {}
variable "key-name" {}
variable "jenkins-name" {}
variable "subnet-elb" {}
variable "cert-arn" {}
variable "nexus-ip" {}
variable "nr-key" {}
variable "nr-acc-id" {}
variable "nr-region" {}